spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: 587
    username: ${SMTP_USERNAME:er.sushantggmail.com}
    password: ${SMTP_PASSWORD:Mitansh@456}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group

server:
  port: 8086

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

notification:
  processing:
    interval: 60000 # Process pending notifications every 60 seconds

kafka:
  topics:
    booking-confirmed: booking-confirmed
    booking-cancelled: booking-cancelled
    payment-completed: payment-completed

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html