server:
  port: 8080

spring:
  application:
    name: api-gateway
  webflux:
    static-path-pattern: /webjars/**
  web:
    resources:
      static-locations: classpath:/META-INF/resources/webjars/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      # default-filters:
      #   - name: RequestRateLimiter
      #     args:
      #       redis-rate-limiter.replenishRate: 10
      #       redis-rate-limiter.burstCapacity: 20
      #       redis-rate-limiter.requestedTokens: 1
      #       key-resolver: "#{@userKeyResolver}"
    loadbalancer:
      ribbon:
        enabled: false

  redis:
    host: localhost
    port: 6379
    
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/resources
    livereload:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

jwt:
  secret: your-secure-jwt-secret-key-for-hs512-algorithm-minimum-64-characters-required-for-security
  
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    enabled: false  # Disable gateway's own API docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    config-url: /api-docs/swagger-config
